### ISSUE TITLE
Cannot find issue_token using instructions

### ISSUE THREAD

**Issue by samyules** [mattsch/badnest#13]
I have followed the instructions multiple times. When I filter the network tab in developer tools by issueToken, nothing ever populates. I was able to find the cookie, but not the token. I am using Vivaldi 3.1.1929.40 on Arch Linux.

**Comment by samyules** [comment]
I use google 2FA. Could that be the issue?

**Comment by DevinKott** [comment]
@samyules I also use 2FA and still receive the packet. Can you try a different browser?

**Comment by samyules** [comment]
I downloaded Google Chrome browser, and I was able to find the packet. Case closed. Now I'm having the same problem as issue #11 ...
