### ISSUE TITLE
Change sensor being used

### ISSUE THREAD

**Issue by busheezy** [mattsch/badnest#18]
I have multiple sensors and I have been trying to figure out if it is possible to change which sensor nest is using.

Any ideas?

Thanks

https://share.busheezy.dev/MPqd08.png

**Comment by mattsch** [comment]
Not possible with this integration.

**Comment by busheezy** [comment]
Okay, thanks

**Comment by eharting** [comment]
Is it not available in the current API? Or does RedDragon’s integration not support it?

**Comment by eharting** [comment]
@busheezy have you found a solution elsewhere?

**Comment by mattsch** [comment]
Please use the forum thread to ask usage questions.
