### ISSUE TITLE
Integration sees both my thermostats but only the Nest E works. The Gen 3 Nest shows with a red circle arrow around an exclamation mark in my entities. When I put my mouse over it it says restored. When I add it to the thermostat card it says unavailable. THe thermostat itself is working fine and I can control it with the Nest App

### ISSUE THREAD

**Issue by gusnieves** [mattsch/badnest#19]
![Issue1-1](https://user-images.githubusercontent.com/48161973/88347912-ffefbf00-cd19-11ea-9540-a31eb9122e09.PNG)
![Issue1-2](https://user-images.githubusercontent.com/48161973/88347915-00885580-cd1a-11ea-9374-44c4ea1fffa0.PNG)

**Comment by mattsch** [comment]
Logs would be helpful, but you're likely to have the best luck on the forum thread since I don't have a thermostat and can't test that particular part.
