### ISSUE TITLE
Nest (Yale) Lock Support?

### ISSUE THREAD

**Issue by kyotodesertfox** [mattsch/badnest#20]
I see the current modules available seem to be:

- Sensor
- Climate (Thermostat)
- Camera (Hello)

I do not see a module that might support for a 'Lock', however; is such an integration possible to support this?

For reference: https://store.google.com/us/product/nest_x_yale_lock

**Comment by mattsch** [comment]
I don't have one so couldn't add, open to merging any pull request to add it however.

**Comment by jschwalbe** [comment]
Just an FYI - there's this: https://github.com/chrisjshull/homebridge-nest/blob/master/lib/nest-lock-accessory.js 
not sure how easy it would be to translate the code.
