### ISSUE TITLE
Add support for Nest Guard / Nest Secure

### ISSUE THREAD

**Issue by danimal4k** [mattsch/badnest#21]
It would be awesome if support could be added for Nest Guard / Nest Secure:

https://store.google.com/us/product/nest_secure_alarm_system

I'm specifically interested in the door sensors.

**Comment by danimal4k** [comment]
I'm fairly technical, I can hack python code but have no experience with these codebases or devices - would be willing to pair / partner with someone who knows the systems (and python) better than me.

**Comment by mattsch** [comment]
Happy to review and include from pull requests, but can't test or anything since I don't have those devices.
