### ISSUE TITLE
I have two devices but only the first one shows.

### ISSUE THREAD

**Issue by Adam-North** [mattsch/badnest#24]
I know you can't test multiples devices as you only have one but I'm hoping someone will be able to figure it out. 

My device that shows up is an older model and it shows as https://home.nest.com/thermostat_{Serial_Number}. My second device was bought after Google took over nest and it shows as https://home.nest.com/thermostat/DEVICE_{Device_ID} on the website.

 I'm hoping someone more knowledgeable than me can figure out a solution.

**Comment by mattsch** [comment]
This probably has to do with some of the protobuf changes in the upstream API. I'd love to dig in and update to use that but not sure I'll have the time before they (hopefully) release a full API that can be used officially. There are some posts in the forums about workarounds some have found useful.
