### ISSUE TITLE
Unable to install on HASS 0.114.2

### ISSUE THREAD

**Issue by backslashV** [mattsch/badnest#25]
Hi,
After adding the URL to HACS, I press the install button on badnest and restart HASS but nothing gets installed.

**Comment by codahq** [comment]
Is there any workaround for this?

**Comment by sym0nd0** [comment]
I'd guess you can manually install the custom component to HA from this repo.

**Comment by mattsch** [comment]
Your best bet is to ask on the forums, there's no blockers to installing via HACS that I'm aware of so nothing to be changed in this repo.
