### ISSUE TITLE
Add hvac_mode controls

### ISSUE THREAD

**Issue by rjmcfadd** [mattsch/badnest#27]
Is it possible to add hvac_mode to the attributes? Currently, hvac_modes shows auto, heat, cool, off but it is just a list of available modes and doesn't allow selection. If you can add hvac_mode, we would be able to select the mode.

https://developers.home-assistant.io/docs/core/entity/climate/

Thank you!

**Comment by jhujasonw** [comment]
I believe that `hvac_mode` is the list of supported modes.  The attribute you are looking for, if you are looking for the currently active mode, is `hvac_action`  To set the mode, you call the service `climate.set_hvac_mode` and pass it the proper parameters.

**Comment by mattsch** [comment]
I'm not using or maintaining this anymore since the combination of the native solution and homebridge plugin is far less fragile and actually works. I'll be updating this repo accordingly.
