### ISSUE TITLE
Nest protect sensors not updating

### ISSUE THREAD

**Issue by robgardien** [mattsch/badnest#29]
I've succesfully included both my Nest Protects, but the sensors for CO and Smoke are not updating. My config has a scan_interval setting:

sensor:
  - platform: badnest
    scan_interval: 10

But last shown shows 21 hours:

![image](https://user-images.githubusercontent.com/12626491/93860995-24d3c480-fcc0-11ea-9d1c-b28d13cbc823.png)

Is there anything else I can do besides the scan_interval setting?

**Comment by mattsch** [comment]
That's just the last time it changed. As luck would have it, steam set one of my protects off today and it did update the status of the device in Hass.

**Comment by robgardien** [comment]
Oke thanks!
