### ISSUE TITLE
Service 'set_temperature' fails when hvac_mode is specified

### ISSUE THREAD

**Issue by mastakebob** [mattsch/badnest#34]
First github issue submission, so I apologize in advance if I miss something or do something wrong:

#### Issue description
The 'set_temperature' service call fails when the `hvac_mode` entry is included.  'set_temperature' service call works when you just include `temperature` (or the `target_temp_high` and `target_temp_low`).  Putting in an `hvac_mode` call causes the service call to completely fail.  Calling `set_hvac_mode` and then `set_temperature` (with just temperature info) separately works.  

The Thermostat lovelace card works as expected.  

Badnest v0.0.4.  HA v0.117.5

#### Steps to reproduce the issue

1.  Turn off your Nest thermostat (for me, `climate.dining_room_thermostat`)
2.   In Developer Tools->Services, select Service `climate.set_temperature` and Entity `climate.dining_room_thermostat`
3.   In data, enter:
`entity_id: climate.dining_room_thermostat
temperature: 65
hvac_mode: heat`
4.  Press "Call Service"

#### What's the expected result?
The Nest thermostat turns to Heat mode with a temp of 65F

#### What's the actual result?
The Nest thermostat does nothing.  There is no error returned (as there would be if you had an invalid hvac_mode entry or something).  

#### Additional details / screenshot
The Thermostat lovelace card works as expected.  Calling the set_temperature service with just temperature information works correctly.  Calling the set_hvac_mode with just hvac_mode works correctly.  Just can't have both hvac_mode and temperature at the same time in set_temperature.  
I turned on debug logging for custom_components.badnest but didn't see anything being logged.

**Comment by mattsch** [comment]
I'm not using or maintaining this anymore since the combination of the native solution and homebridge plugin is far less fragile and actually works. I'll be updating this repo accordingly.
