### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by BartEngelen** [mattsch/badnest#35]
Hello,
Is it also possible to get more sensors from the Nest Protect ?
Now I only have:
Battery Health State --> ok
CO Status --> ok
Smoke Status --> ok

If it is possible I would have some extra sensors:
Online Status
Color Status
...

Thanks

**Comment by mattsch** [comment]
I'm not using or maintaining this anymore since the combination of the native solution and homebridge plugin is far less fragile and actually works. I'll be updating this repo accordingly.
