### ISSUE TITLE
2nd thermostat unavailable

### ISSUE THREAD

**Issue by jscherry** [mattsch/badnest#36]
I have 2 thermostats, 2 temp sensors, 4 protects. About 9 months ago one thermostat dropped out as unavailable. I just went in and updated the token and cookie. Everything is back except for the thermostat that dropped off 9 months ago. It still just shows as unavailable for the temp and thermostat. What can I do to fix this?

**Comment by mattsch** [comment]
I'm not using or maintaining this anymore since the combination of the native solution and homebridge plugin is far less fragile and actually works. I'll be updating this repo accordingly.
