### ISSUE TITLE
Camera has no stream source

### ISSUE THREAD

**Issue by maxclaey** [mattsch/badnest#4]
First of all, thanks for following up on this integration after the original repo has gone stale!

I am using this integration to control my thermostat and nest hello camera through home assistant. Both are exposed to homekit as well. I can correctly get a snapshot of the camera, but opening it fails, both in the home assistant frontend, as in the apple home app. When trying to open the camera in the apple home app, I get the error "Camera has no stream source" in my home assistant logs. As far as I understand, the nest camera integration only supports snapshotting, not streaming. Is this correct? Is this something that can be added, or is this not exposed as in the API?

**Comment by mattsch** [comment]
I'm not aware of any way to stream right now, but I'll keep this open in case I find something.

**Comment by maxclaey** [comment]
Ok, cool! I think there is an approach somewhere in home assistant where an MJPEG stream can be setup based on consecutive snapshots of the camera, but that would require at least 1 (preferably more) snapshots per second. But I guess there is a reason why only 1 snapshot per 30 seconds is allowed right now? If not, I could have a look at it

**Comment by Jay2645** [comment]
@mattsch I would take a look at the [slinkymanbyday](https://github.com/slinkymanbyday/badnest) fork, as there's a number of differences with regards to how cameras are handled between the two. I didn't look terribly closely, but it does seem to handle my Nest Hello better.

**Comment by mattsch** [comment]
I'm not using or maintaining this anymore since the combination of the native solution and homebridge plugin is far less fragile and actually works. I'll be updating this repo accordingly.
