### ISSUE TITLE
Expose Protect motion detection

### ISSUE THREAD

**Issue by ahertz** [mattsch/badnest#6]
Based on [this issue from homebridge-nest](https://github.com/chrisjshull/homebridge-nest/issues/254) (which I've never used but appears to use the same "API" as badnest), it looks like it might be possible to read the state of the motion detector in a hardwired Protect.  Would it be possible to expose that to Home Assistant as a binary sensor?

I'm more than happy to try to get this working myself, but figured I'd put in an issue in case someone's already looked at it and decided it doesn't work for some reason.

**Comment by mattsch** [comment]
It's likely the API does support it, but I don't have the hardware so I can't test. Happy to include working code if you do decide to dig in.

**Comment by mattsch** [comment]
I'm not using or maintaining this anymore since the combination of the native solution and homebridge plugin is far less fragile and actually works. I'll be updating this repo accordingly.
